---
  - name: Power up the PowerEdge - Lab
    hosts: idrac         # group to target
    connection: local    # required - to access the python "omsdk". To install (assuming ansible is running on "python3"),
                        # python3 -m pip install osmdk --upgrade
    gather_facts: no     # this would gather_facts about the localhost (connection: local). We want facts / info about the IDRAC
  
    collections:
      - dellemc.openmanage
       
    vars:
     
            idrac_user: root      # this value needs mapped (ex. admin)
            idrac_password: r0gerwilc0    # this value needs mapped (ex. qwerty123)
            reset_type: "On"

    tasks:

          - name: Power Up 
            redfish_powerstate:
                 baseuri: "{{ idrac_ip }}"
                 username: "{{ idrac_user }}"
                 password: "{{ idrac_password }}"
                 validate_certs: False
                 reset_type: "{{ reset_type }}"
            register: results    # save all of the returned info within the var "results"

          - name: Display power info
            debug:
                  var: results       



