  # Precheck
  - name: Assert that an expected condition is true (this is a chicago asset)
    assert:
      that:
          - "'Chicago' in results.redfish_facts.system.entries[0][1].AssetTag"
      success_msg: "Confirmed a Chicago asset"

  - name: Ensure the correct model is being used
    assert:
      that:
        - results.redfish_facts.system.entries[0][1].Model == "3500"
      success_msg: "Confrimed model 3500"
      fail_msg: "This does not appear to be a model 3500. Aborting."

  - name: Ensure the power state of the system is on
    assert:
      that:
        - results.redfish_facts.system.entries[0][1].PowerState == "On"
      success_msg: "Confirmed system is powered on"
      fail_msg: "The system is not powered on. Aborting."

  - name: Ensure the system is healthy
    assert:
      that:
        - results.redfish_facts.system.entries[0][1].Status.Health == "OK"
      success_msg: "Confirmed system is heatlhy"
      fail_msg: "The system is not heatlhy. Aborting."
